package dev.cobblesword;

public enum TokenType {
    IDENTIFIER, STRING, NUMBER,
    IMPORT, FUNC, MODULE, TYPE, VALUE, HANDLER, EXPOSE, RETURN,
    LPAREN, RPAREN, LBRACE, RBRACE, COLON, SEMICOLON, COMMA, ASSIGN, ARROW,
    DOT, NEWLINE, EOF
}